#! /bin/sh

id=$(docker image ls | awk '{ if($1=="handshake-mailserver") print $3 }')
ver="$(date +%Y-%m-%d)"
if test "$1"; then ver="$1"; fi

docker tag ${id} jamesstevens/handshake-mailserver
docker push jamesstevens/handshake-mailserver

docker tag ${id} jamesstevens/handshake-mailserver:${ver}
docker push jamesstevens/handshake-mailserver:${ver}
