#! /bin/sh

find /run/sessions/ -mtime +1 -delete

svr_pem="${BASE:-/opt/data}/pems/server.pem"
svr_dst="run/pems/server.pem"
if test -f ${svr_pem} -a ${svr_pem} -nt ${svr_dst}
	then
		cp -a ${svr_pem} ${svr_dst}
		killall -HUP stunnel nginx
		postfix reload
	fi
