#! /bin/sh

. /usr/local/bin/inc

src="${BASE}/pems/server.pem"
dst="/run/pems/server.pem"
if test -s ${src} -a ${src} -n ${dst}
	then
		{
		cp -av ${src} ${dst}
		/usr/sbin/postfix reload
		} | logger -t update_server_pem
	fi
