#! /bin/sh

. /usr/local/bin/inc

svr_pem="${BASE}/pems/server.pem"
svr_dst="/run/pems/server.pem"
if test -f ${svr_pem} -a ${svr_pem} -nt ${svr_dst}
	then
		cp -a ${svr_pem} ${svr_dst}
		killall -HUP nginx
		killall stunnel
		postfix reload
	fi

find ${BASE}/service/reset_codes/. -mtime +0 -type f -delete
